var area_list=[];
area_list[0]="全国";
area_list[1]="北京";
area_list[2]="天津";
area_list[3]="重庆";
area_list[4]="上海";

area_list[5]="河北";
area_list[6]="四川";
area_list[7]="江苏";
area_list[8]="浙江";
area_list[9]="吉林";
area_list[10]="黑龙江";

area_list[11]="内蒙古";
area_list[12]="辽宁";
area_list[13]="安徽";
area_list[14]="福建";
area_list[15]="江西";
area_list[16]="山东";
area_list[17]="河南";
area_list[18]="湖北";
area_list[19]="湖南";
area_list[20]="广东";
area_list[21]="广西";
area_list[22]="海南";

area_list[23]="山西";
area_list[24]="贵州";
area_list[25]="云南";
area_list[26]="西藏";
area_list[27]="陕西";
area_list[28]="甘肃";
area_list[29]="青海";
area_list[30]="宁夏";
area_list[31]="新疆";
area_list[32]="台湾";
area_list[32]="香港";
area_list[33]="澳门";